# Generated by Django 5.1.6 on 2025-05-15 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nysc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=100, verbose_name='Last Name')),
                ('other_name', models.CharField(help_text='Enter your last name', max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('capturing', models.BooleanField(default=False, help_text='Do you need capturing?', verbose_name='Capturing')),
                ('passport', models.BooleanField(default=False, help_text='Do you need passport?', verbose_name='Passport')),
                ('medical_certificate', models.BooleanField(default=False, help_text='Do you want medical certificate?', verbose_name='Medical Certificate')),
                ('concord_printing', models.BooleanField(default=False, help_text='Do you want medical certificate?', verbose_name='Medical Certificate Concord pronting')),
                ('slot', models.SlugField()),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
