# Generated by Django 5.1.6 on 2025-05-27 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('batch', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, null=True)),
                ('stream', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, null=True)),
                ('last_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Nysc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('capturing', models.BooleanField(default=False, verbose_name='Capturing')),
                ('call_up', models.BooleanField(default=False, verbose_name='Call Up Letter')),
                ('passport', models.BooleanField(default=False, verbose_name='Passport Photograph')),
                ('medical_certificate', models.BooleanField(default=False, verbose_name='Medical Fitness Certificate')),
                ('concord_printing', models.BooleanField(default=False, verbose_name='Medical Certificate Concord printing')),
                ('slot', models.SlugField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
