# Generated by Django 5.1.6 on 2025-05-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='last_no',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='batch',
            name='stream',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2, null=True),
        ),
    ]
