# Generated by Django 5.1.6 on 2025-09-05 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='nysc',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Enter a valid email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
    ]
