# Generated by Django 5.1.6 on 2025-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nysc',
            name='call_up',
            field=models.BooleanField(default=False, verbose_name='Call Up Letter'),
        ),
        migrations.AlterField(
            model_name='nysc',
            name='capturing',
            field=models.BooleanField(default=False, verbose_name='Capturing'),
        ),
        migrations.AlterField(
            model_name='nysc',
            name='concord_printing',
            field=models.BooleanField(default=False, verbose_name='Medical Certificate Concord printing'),
        ),
        migrations.AlterField(
            model_name='nysc',
            name='medical_certificate',
            field=models.BooleanField(default=False, verbose_name='Medical Fitness Certificate'),
        ),
        migrations.AlterField(
            model_name='nysc',
            name='other_name',
            field=models.CharField(help_text='Enter your last name', max_length=100, verbose_name='Other Name'),
        ),
        migrations.AlterField(
            model_name='nysc',
            name='passport',
            field=models.BooleanField(default=False, verbose_name='Passport Photograph'),
        ),
    ]
