# Generated by Django 5.1.6 on 2025-03-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nysc',
            name='capturing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nysc',
            name='medical',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nysc',
            name='passport',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nysc',
            name='payment_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
