# Generated by Django 5.1.6 on 2025-09-05 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0002_alter_batch_batch_alter_nysc_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nysc',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
    ]
