# Generated by Django 5.1.6 on 2025-05-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0002_alter_batch_batch_alter_batch_last_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='last_no',
            field=models.IntegerField(default=0),
        ),
    ]
