# Generated by Django 5.1.6 on 2025-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0002_nysc_capturing_nysc_medical_nysc_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nysc',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
