# Generated by Django 5.1.6 on 2025-05-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0003_alter_batch_last_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='nysc',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
