# Generated by Django 5.1.6 on 2025-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0004_nysc_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nysc',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
