# Generated by Django 5.1.6 on 2025-07-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sample',
            field=models.ImageField(blank=True, null=True, upload_to='Prototype/'),
        ),
    ]
