# Generated by Django 5.1.6 on 2025-07-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.CharField(blank=True, choices=[('SHORT SLEEVE', 'SHORT SLEEVE'), ('LONG SLEEVE', 'LONG SLEEVE')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('xs', 'xs'), ('xm', 'xm'), ('xl', 'xl')], max_length=100, null=True),
        ),
    ]
