# Generated by Django 5.1.6 on 2025-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderitem_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
