# Generated by Django 5.1.6 on 2025-07-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='colour',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='length',
            field=models.CharField(blank=True, choices=[('SHORT SLEEVE', 'SHORT SLEEVE'), ('LONG SLEEVE', 'LONG SLEEVE')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, choices=[('xs', 'xs'), ('xm', 'xm'), ('xl', 'xl')], max_length=100, null=True),
        ),
    ]
